"""Compliance evidence report generator — SOC 2 (Sprint 4 per PLAN.md) plus
HIPAA/PCI-DSS/EU AI Act (Phase 2 enterprise tier, proposal §7.2, added
2026-09-27 — see PROGRESS.md). Renamed from soc2_report.py when this
generalized beyond one framework; --framework soc2 is still the default,
so `python compliance_report.py --format pdf` behaves exactly as
soc2_report.py always did.

Pulls from the existing audit-logger/circuit-breaker endpoints (no new
endpoints added anywhere) and renders a report mapping observed AEGIS
behavior to the control IDs documented in the framework's own mapping
file:
  - CONTROL_MAPPING.md      (SOC 2 Trust Services Criteria)
  - HIPAA_MAPPING.md        (HIPAA Security/Administrative Safeguards)
  - PCI_DSS_MAPPING.md      (PCI-DSS v4.0)
  - EU_AI_ACT_MAPPING.md    (EU AI Act Articles 9-15)
See whichever mapping file matches --framework for the rationale AND its
disclaimer, which this report repeats on its own cover page: this is
evidence supporting a compliance conversation, not a certification. Only
a licensed/accredited assessor (a CPA firm for SOC 2, a QSA for PCI-DSS,
etc.) can issue an actual one.

Standalone script, not a service — no Dockerfile, not part of
docker-compose.yml, matching demo/*.py's convention. Run it directly
against a running stack:

    pip install -r requirements.txt
    python compliance_report.py --framework hipaa --tenant default --format pdf

Reads AEGIS_AUDIT_URL / AEGIS_CIRCUIT_BREAKER_URL from the environment
(same names as aegisctl and every other host-side tool in this repo,
default http://localhost:<port> — see docs/configuration.md's
host-vs-in-network URL nuance).
"""

import argparse
import json
import os
import sys
from collections import Counter
from datetime import datetime, timezone

import urllib.error
import urllib.request

AUDIT_URL = os.environ.get("AEGIS_AUDIT_URL", "http://localhost:9300")
BREAKER_URL = os.environ.get("AEGIS_CIRCUIT_BREAKER_URL", "http://localhost:9400")

SOC2_DISCLAIMER = (
    "This report is evidence generated by AEGIS to SUPPORT a SOC 2 Type II "
    "audit. It is NOT a certification and does not substitute for an "
    "examination by a licensed CPA firm. A real SOC 2 Type II report "
    "covers an observation period (typically 3-12 months) and includes "
    "organizational controls (HR, physical security, vendor management, "
    "etc.) that AEGIS has no visibility into. This report covers only the "
    "slice of the Trust Services Criteria relevant to AI agent "
    "containment, based on whatever is in the audit log at the time this "
    "report was generated. See CONTROL_MAPPING.md for the full mapping "
    "and its own disclaimer."
)

HIPAA_DISCLAIMER = (
    "This report is evidence generated by AEGIS to SUPPORT a HIPAA "
    "Security Rule compliance conversation. It is NOT a certification — "
    "HIPAA has no third-party certification body at all, and this report "
    "does not substitute for your own compliance/legal review. It covers "
    "only the technical (and a few administrative) safeguards a runtime "
    "containment layer can produce evidence for, based on whatever is in "
    "the audit log at the time this report was generated. AEGIS's PII "
    "detection is NOT the same thing as PHI detection — see "
    "HIPAA_MAPPING.md for the full mapping and its own disclaimer."
)

PCI_DSS_DISCLAIMER = (
    "This report is evidence generated by AEGIS to SUPPORT a PCI-DSS v4.0 "
    "compliance conversation. It is NOT a Report on Compliance and does "
    "not substitute for an assessment by a Qualified Security Assessor. "
    "It covers only the slice of PCI-DSS requirements relevant to an AI "
    "agent that might touch cardholder data, based on whatever is in the "
    "audit log at the time this report was generated. See "
    "PCI_DSS_MAPPING.md for the full mapping and its own disclaimer, "
    "including exactly what AEGIS's credit-card detection is and isn't."
)

EU_AI_ACT_DISCLAIMER = (
    "This report is evidence generated by AEGIS to SUPPORT an EU AI Act "
    "conformity conversation for a high-risk AI system. It is NOT a "
    "conformity assessment and does not substitute for one. It covers "
    "only the slice of Articles 9-15 a runtime containment layer can "
    "produce evidence for, based on whatever is in the audit log at the "
    "time this report was generated — training-data governance (Article "
    "10), conformity assessment procedures (Article 43), and fundamental "
    "rights impact assessments (Article 27) are out of scope. See "
    "EU_AI_ACT_MAPPING.md for the full mapping and its own disclaimer."
)

# Keep each list in sync with its mapping file by hand — see that file's
# own note that IT is the single source of truth these control
# IDs/titles are meant to mirror. static_text=None means _control_evidence
# below fills it in dynamically from the aggregated evidence.
SOC2_CONTROLS = [
    ("CC6.1", "Logical access is restricted to authorized users",
     "Every action is evaluated against tenant-scoped OPA policy (packages/policy-engine) before it executes."),
    ("CC6.6", "Least-privilege access is enforced",
     "Actions are allow-listed (allowed_tools, allowed_credential_actions) rather than deny-listed."),
    ("CC6.8", "Unauthorized/malicious destinations are restricted",
     "Network egress is evaluated against an explicit allowed_domains list; non-listed destinations are denied."),
    ("CC7.1", "Configuration/change baselines are monitored",
     "Policy changes are applied via aegisctl policy apply and are themselves audit-logged."),
    ("CC7.2", "The system monitors for anomalies", None),
    ("CC7.3", "Security incidents are evaluated and responded to", None),
    ("CC7.4", "Incident response includes recovery/remediation", None),
    ("PI1.4", "Processing is complete, accurate, and verifiable", None),
    ("C1.1", "Confidential information access is restricted", "Credential vaulting: agents never hold, see, or transmit raw credentials (packages/credential-vault)."),
    ("C1.2", "Confidential information is protected from disclosure", "Per-tenant Vault paths with no cross-tenant fallback; a missing tenant secret hard-fails rather than resolving to another tenant's credential."),
]

HIPAA_CONTROLS = [
    ("§164.312(a)(1)", "Access Control", "Every action is evaluated against tenant-scoped OPA policy (packages/policy-engine) before it executes."),
    ("§164.312(a)(2)(i)", "Unique User Identification", "Every action carries tenant_id/session_id, verified fully isolated per tenant even under a shared session_id string across tenants."),
    ("§164.312(b)", "Audit Controls", None),
    ("§164.312(c)(1)", "Integrity", None),
    ("§164.312(d)", "Person or Entity Authentication", "Dashboard API static keys (config.py's DASHBOARD_API_KEYS) resolve to a tenant AND a named operator identity; both derived server-side from the key, never client-supplied."),
    ("§164.312(e)(1)", "Transmission Security", "Egress control (packages/proxy) plus the DNS-rebinding fix (packages/proxy/dns-filter) rejecting private/loopback/link-local DNS answers before any connection is attempted."),
    ("§164.308(a)(1)(ii)(D)", "Information System Activity Review", None),
    ("§164.308(a)(6)(ii)", "Response and Reporting", None),
    ("HIPAA-CG", "Outbound PII/PHI-adjacent text screening (content-guardrail)", None),
]

PCI_DSS_CONTROLS = [
    ("Req 1", "Network security controls", "Deny-by-default egress control (packages/proxy) plus the DNS-rebinding fix (packages/proxy/dns-filter)."),
    ("Req 3", "Protect stored account data", None),
    ("Req 7", "Restrict access by business need to know", "allowed_tools/allowed_credential_actions allowlists; per-tenant Vault paths with no cross-tenant fallback."),
    ("Req 8", "Identify users and authenticate access", "Dashboard API static keys resolve to a tenant, role, and named operator identity; tenant_id/session_id scoping verified isolated per tenant."),
    ("Req 10", "Log and monitor all access", None),
    ("Req 10.5", "Audit logs are protected from tampering", None),
    ("PCI-CG", "Cardholder-data-shaped (PAN) text screening (content-guardrail)", None),
]

EU_AI_ACT_CONTROLS = [
    ("Article 9", "Risk management system", "Layered containment (egress control, credential vaulting, action-level policy, anomaly detection, circuit-breaker escalation, content guardrails) addressing distinct risk categories rather than one mechanism covering all of them."),
    ("Article 12", "Record-keeping", None),
    ("Article 14", "Human oversight", None),
    ("Article 15", "Accuracy, robustness, and cybersecurity",
     "packages/anomaly-detector's trained classifier (evaluated on a held-out synthetic split) plus packages/content-guardrail's prompt-injection detection, measured against a curated adversarial set: 12/12 known-technique recall, 3/4 mechanical-evasion techniques defeated, one genuine semantic paraphrase honestly confirmed as NOT caught — see packages/content-guardrail/README.md's Adversarial testing section."),
    ("Article 13", "Transparency to deployers", "Every action's allow/deny decision is logged with its reason; aegisctl logs and the dashboard surface this directly."),
]

FRAMEWORKS = {
    "soc2": {"title": "SOC 2", "disclaimer": SOC2_DISCLAIMER, "controls": SOC2_CONTROLS},
    "hipaa": {"title": "HIPAA", "disclaimer": HIPAA_DISCLAIMER, "controls": HIPAA_CONTROLS},
    "pci-dss": {"title": "PCI-DSS", "disclaimer": PCI_DSS_DISCLAIMER, "controls": PCI_DSS_CONTROLS},
    "eu-ai-act": {"title": "EU AI Act", "disclaimer": EU_AI_ACT_DISCLAIMER, "controls": EU_AI_ACT_CONTROLS},
}


def _get_json(url: str):
    with urllib.request.urlopen(url, timeout=10) as resp:
        return json.loads(resp.read())


def fetch_events(tenant: str, limit: int) -> list:
    return _get_json(f"{AUDIT_URL}/events?tenant_id={tenant}&limit={limit}")


def fetch_verify(tenant: str) -> dict:
    return _get_json(f"{AUDIT_URL}/verify?tenant_id={tenant}")


def fetch_suspended(tenant: str) -> list:
    return _get_json(f"{BREAKER_URL}/suspended?tenant_id={tenant}")


def _in_range(event: dict, since: str | None, until: str | None) -> bool:
    ts = event.get("timestamp", "")
    if since and ts < since:
        return False
    if until and ts > until:
        return False
    return True


def aggregate(tenant: str, events: list, verify: dict, suspended: list, since: str | None, until: str | None) -> dict:
    events = [e for e in events if _in_range(e, since, until)]

    sessions = {e.get("session_id") for e in events if e.get("session_id")}
    decisions = [e for e in events if e.get("event_type") == "policy_decision"]
    allowed = [e for e in decisions if (e.get("policy_decision") or {}).get("allowed")]
    denied = [e for e in decisions if not (e.get("policy_decision") or {}).get("allowed")]
    denied_by_type = Counter((e.get("action") or {}).get("action_type", "unknown") for e in denied)

    off_tenant = [e for e in events if e.get("tenant_id") not in (tenant, None)]

    anomaly_suspensions = [s for s in suspended if s.get("reason", "").startswith("anomaly detector:")]
    threshold_suspensions = [s for s in suspended if "policy violations" in s.get("reason", "")]
    terminated = [s for s in suspended if s.get("terminated")]

    # Added for HIPAA/PCI-DSS's content-guardrail evidence rows — real
    # events already logged by packages/content-guardrail
    # (content_guardrail_decision), not a new query mechanism.
    cg_events = [e for e in events if e.get("event_type") == "content_guardrail_decision"]
    cg_categories: Counter = Counter()
    for e in cg_events:
        for m in e.get("matches", []):
            cg_categories[m.get("category", "unknown")] += 1

    return {
        "tenant": tenant,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "range": {"since": since, "until": until},
        "totals": {
            "events": len(events),
            "distinct_sessions": len(sessions),
            "policy_decisions": len(decisions),
            "allowed": len(allowed),
            "denied": len(denied),
            "denied_by_action_type": dict(denied_by_type),
        },
        "tenant_scoping": {
            "events_outside_tenant": len(off_tenant),
            "evidence": (
                f"0 of {len(events)} events carried a different tenant_id"
                if not off_tenant
                else f"WARNING: {len(off_tenant)} events did not match the requested tenant_id"
            ),
        },
        "integrity": verify,
        "incidents": {
            "total_suspended_or_terminated": len(suspended),
            "anomaly_detector_triggered": len(anomaly_suspensions),
            "threshold_triggered": len(threshold_suspensions),
            "permanently_terminated": len(terminated),
            "details": suspended,
        },
        "content_guardrail": {
            "decisions": len(cg_events),
            "by_category": dict(cg_categories),
        },
    }


def _control_evidence(control_id: str, static_text: str | None, agg: dict) -> str:
    if static_text:
        return static_text
    if control_id == "CC7.2":
        return (
            f"{agg['incidents']['anomaly_detector_triggered']} session(s) were flagged and suspended by "
            "the rule-based anomaly detector (packages/anomaly-detector) during this period."
        )
    if control_id == "CC7.3":
        return (
            f"{agg['incidents']['total_suspended_or_terminated']} session(s) were suspended or terminated "
            f"({agg['incidents']['threshold_triggered']} by violation-count threshold, "
            f"{agg['incidents']['anomaly_detector_triggered']} by anomaly detection)."
        )
    if control_id == "CC7.4":
        return (
            f"{agg['incidents']['permanently_terminated']} session(s) were permanently terminated via "
            "human-in-the-loop review (aegisctl deny); all others remain resumable pending review."
        )
    if control_id == "PI1.4" or control_id == "§164.312(c)(1)":
        intact = agg["integrity"].get("chain_intact")
        return (
            f"Hash-chain verification over {agg['totals']['events']} event(s): "
            f"chain_intact={intact}. " + ("No tampering detected." if intact else "TAMPERING DETECTED.")
        )
    if control_id == "§164.312(b)" or control_id == "Req 10":
        return (
            f"{agg['totals']['events']} event(s) recorded for this tenant during this period "
            f"({agg['totals']['policy_decisions']} policy decisions, "
            f"{agg['content_guardrail']['decisions']} content-guardrail checks, "
            f"{agg['incidents']['total_suspended_or_terminated']} circuit-breaker events) — {agg['tenant_scoping']['evidence']}."
        )
    if control_id == "§164.308(a)(1)(ii)(D)":
        return (
            f"{agg['totals']['events']} event(s) available for activity review via aegisctl logs/the dashboard "
            f"for this tenant during this period."
        )
    if control_id == "§164.308(a)(6)(ii)" or control_id == "Article 14":
        return (
            f"{agg['incidents']['total_suspended_or_terminated']} session(s) suspended or terminated "
            f"({agg['incidents']['threshold_triggered']} by violation threshold, "
            f"{agg['incidents']['anomaly_detector_triggered']} by anomaly detection, "
            f"{agg['incidents']['permanently_terminated']} permanently, via human-in-the-loop review) — "
            "all non-terminated suspensions remain resumable pending human review (aegisctl approvals/approve/deny)."
        )
    if control_id == "Req 10.5":
        intact = agg["integrity"].get("chain_intact")
        return (
            f"Hash-chain verification over {agg['totals']['events']} event(s): chain_intact={intact}. "
            + ("No tampering detected." if intact else "TAMPERING DETECTED.")
        )
    if control_id == "HIPAA-CG":
        pii = agg["content_guardrail"]["by_category"].get("pii", 0)
        return (
            f"{agg['content_guardrail']['decisions']} content-guardrail check(s) fired during this period; "
            f"{pii} PII-category match(es) (email/phone/SSN/credit-card-shaped — see HIPAA_MAPPING.md's "
            "PHI-vs-PII scoping note) were masked before reaching a response or the audit log."
        )
    if control_id == "PCI-CG":
        pii = agg["content_guardrail"]["by_category"].get("pii", 0)
        return (
            f"{agg['content_guardrail']['decisions']} content-guardrail check(s) fired during this period; "
            f"{pii} PII-category match(es) (includes Luhn-validated credit-card-shaped sequences) were "
            "masked before reaching a response or the audit log. Not a PAN-discovery guarantee — see "
            "PCI_DSS_MAPPING.md's scoping note."
        )
    if control_id == "Req 3":
        pii = agg["content_guardrail"]["by_category"].get("pii", 0)
        return (
            "Credential vaulting (packages/credential-vault) never lets the agent hold a raw credential. "
            f"Additionally, {pii} PII-category content-guardrail match(es) during this period were masked "
            "before reaching a response or the audit log (see PCI-CG row for detail)."
        )
    if control_id == "Article 12":
        return (
            f"{agg['totals']['events']} event(s) automatically recorded for this tenant during this period, "
            f"hash-chained (chain_intact={agg['integrity'].get('chain_intact')}) — see Article 15's "
            "note on aegisctl replay for lifecycle traceability."
        )
    return "No evidence collected for this control in this run."


def render_markdown(title: str, disclaimer: str, controls: list, agg: dict) -> str:
    lines = [
        f"# AEGIS {title} Evidence Report",
        "",
        f"**Tenant:** {agg['tenant']}  ",
        f"**Generated:** {agg['generated_at']}  ",
        f"**Range:** {agg['range']['since'] or 'earliest available'} to {agg['range']['until'] or 'now'}",
        "",
        f"> {disclaimer}",
        "",
        "## Summary",
        "",
        f"- Total events: {agg['totals']['events']}",
        f"- Distinct sessions: {agg['totals']['distinct_sessions']}",
        f"- Policy decisions: {agg['totals']['policy_decisions']} "
        f"({agg['totals']['allowed']} allowed, {agg['totals']['denied']} denied)",
        f"- Denied by action type: {agg['totals']['denied_by_action_type']}",
        f"- Content-guardrail checks: {agg['content_guardrail']['decisions']} "
        f"(by category: {agg['content_guardrail']['by_category']})",
        f"- Tenant scoping: {agg['tenant_scoping']['evidence']}",
        f"- Sessions suspended/terminated: {agg['incidents']['total_suspended_or_terminated']}",
        "",
        "## Control-by-control evidence",
        "",
    ]
    for control_id, description, static_text in controls:
        lines.append(f"### {control_id} — {description}")
        lines.append("")
        lines.append(_control_evidence(control_id, static_text, agg))
        lines.append("")
    return "\n".join(lines)


def render_json(title: str, disclaimer: str, controls: list, agg: dict) -> str:
    out = dict(agg)
    out["framework"] = title
    out["disclaimer"] = disclaimer
    out["controls"] = [
        {"id": cid, "description": desc, "evidence": _control_evidence(cid, static, agg)}
        for cid, desc, static in controls
    ]
    return json.dumps(out, indent=2)


# fpdf2's core fonts (Helvetica/Times/Courier) only support Latin-1 —
# found by testing, not assumed: generating a real PDF for a control
# whose evidence text used an em dash raised FPDFUnicodeEncodingException
# ("outside the range of characters supported by the font"). This repo's
# own prose style uses em dashes/curly quotes throughout, so rather than
# scrub every control string of normal punctuation, PDF rendering
# transliterates the common typographic characters fpdf2's core fonts
# can't handle to their plain-ASCII equivalents — markdown/json output
# are untouched (real UTF-8, no font limitation there).
_PDF_UNSAFE_CHARS = {
    "—": "-",  # em dash
    "–": "-",  # en dash
    "‘": "'",  # left single quote
    "’": "'",  # right single quote
    "“": '"',  # left double quote
    "”": '"',  # right double quote
    "…": "...",  # ellipsis
}


def _pdf_safe(text: str) -> str:
    for char, replacement in _PDF_UNSAFE_CHARS.items():
        text = text.replace(char, replacement)
    return text


def render_pdf(title: str, disclaimer: str, controls: list, agg: dict, output_path: str) -> None:
    from fpdf import FPDF  # deferred import — only needed for --format pdf, see requirements.txt

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)

    def mc(h, text):
        # fpdf2's multi_cell defaults to new_x=RIGHT, which for a
        # full-width (w=0) cell leaves the cursor at the *right* margin —
        # the next call then has ~0 width left and raises
        # "Not enough horizontal space to render a single character".
        # Explicitly reset back to the left margin after every line.
        pdf.multi_cell(0, h, _pdf_safe(text), new_x="LMARGIN", new_y="NEXT")

    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    mc(10, f"AEGIS {title} Evidence Report")
    pdf.set_font("Helvetica", "", 11)
    pdf.ln(2)
    mc(6, f"Tenant: {agg['tenant']}")
    mc(6, f"Generated: {agg['generated_at']}")
    mc(6, f"Range: {agg['range']['since'] or 'earliest available'} to {agg['range']['until'] or 'now'}")
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 9)
    mc(5, disclaimer)

    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 13)
    mc(8, "Summary")
    pdf.set_font("Helvetica", "", 10)
    summary_lines = [
        f"Total events: {agg['totals']['events']}",
        f"Distinct sessions: {agg['totals']['distinct_sessions']}",
        f"Policy decisions: {agg['totals']['policy_decisions']} "
        f"({agg['totals']['allowed']} allowed, {agg['totals']['denied']} denied)",
        f"Denied by action type: {agg['totals']['denied_by_action_type']}",
        f"Content-guardrail checks: {agg['content_guardrail']['decisions']} "
        f"(by category: {agg['content_guardrail']['by_category']})",
        f"Tenant scoping: {agg['tenant_scoping']['evidence']}",
        f"Sessions suspended/terminated: {agg['incidents']['total_suspended_or_terminated']}",
    ]
    for line in summary_lines:
        mc(6, f"- {line}")

    for control_id, description, static_text in controls:
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 12)
        mc(7, f"{control_id} - {description}")
        pdf.set_font("Helvetica", "", 10)
        mc(6, _control_evidence(control_id, static_text, agg))

    pdf.output(output_path)


def main():
    parser = argparse.ArgumentParser(description="Generate an AEGIS compliance evidence report.")
    parser.add_argument("--framework", choices=list(FRAMEWORKS), default="soc2")
    parser.add_argument("--tenant", default="default")
    parser.add_argument("--since", default=None, help="ISO timestamp, inclusive lower bound")
    parser.add_argument("--until", default=None, help="ISO timestamp, inclusive upper bound")
    parser.add_argument("--limit", type=int, default=1000, help="max events to pull from the audit log")
    parser.add_argument("--format", choices=["pdf", "markdown", "json"], default="pdf")
    parser.add_argument("--output", default=None, help="output file path (default: auto-named)")
    args = parser.parse_args()

    framework = FRAMEWORKS[args.framework]

    try:
        events = fetch_events(args.tenant, args.limit)
        verify = fetch_verify(args.tenant)
        suspended = fetch_suspended(args.tenant)
    except (urllib.error.URLError, OSError) as exc:
        print(f"error: could not reach AEGIS services ({exc}). Is the stack running?", file=sys.stderr)
        sys.exit(1)

    agg = aggregate(args.tenant, events, verify, suspended, args.since, args.until)

    ext = {"pdf": "pdf", "markdown": "md", "json": "json"}[args.format]
    # soc2's default filename is unchanged from the pre-rename soc2_report.py
    # for anyone with that exact command in a script/README already.
    prefix = "soc2_report" if args.framework == "soc2" else f"{args.framework.replace('-', '_')}_report"
    output_path = args.output or f"{prefix}_{args.tenant}.{ext}"

    # Found by testing, not assumed: this repo's own prose style uses em
    # dashes/curly quotes throughout the new HIPAA/PCI-DSS/EU AI Act
    # control text, and Python's open() defaults to the platform locale
    # encoding, not UTF-8 — on Windows that mangled them on write.
    # Explicit encoding="utf-8" here, independent of _pdf_safe (which
    # only affects the PDF path's font limitation, not this).
    if args.format == "markdown":
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(render_markdown(framework["title"], framework["disclaimer"], framework["controls"], agg))
    elif args.format == "json":
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(render_json(framework["title"], framework["disclaimer"], framework["controls"], agg))
    else:
        render_pdf(framework["title"], framework["disclaimer"], framework["controls"], agg, output_path)

    print(f"wrote {output_path}")


if __name__ == "__main__":
    main()
